### PR TITLE
interleaveMany

### PR DESCRIPTION
**Pull request by BlackCapCoder**
`interleaveMany = foldr1 interleave` but about 30% faster and with 20% less `malloc` calls. That's not a huge improvement, but an improvement non the less!

```haskell
interleaveMany :: Infinite (Infinite a) -> Infinite a
```
It is strict in the first 64 elements of the "outer" infinite list, but lazy in the the "inner" ones.

It is possible to make the outer list finite, ie `NonEmpty (Infinite a) -> Infinite a`, by capping the index to however many elements there are ```i = 63 `min` ctz x `min` length lists - 1```.

### CODE REVIEW

**Comment by BlackCapCoder** [comment]
I am going to bundle `interleaves` with `interleaveMany`.

Whereas `interleave` and `interleaveMany` interleaves 2 lists at a time, `interleaves` interleaves N lists.

When `N` is a power of 2, it is possible to emulate `interleaves` using `interleave`:
```haskell
-- (~~) = interleave
--
--                        0
--                      0 ~~ 1
--               (0 ~~ 2) ~~ (1 ~~ 3)
-- ((0 ~~ 4) ~~ (2 ~~ 6)) ~~ ((1 ~~ 5) ~~ (3 ~~ 7))
-- ...
```
The number at each index is the bit representation of the index in reverse.

When N is not a power of 2, `interleaves` does something that `interleave` cannot!

**Comment by BlackCapCoder** [comment]
> Having `interleaves` we can now make all possible "interleavings", and it would be very nice if we could somehow factorize things like the example above into using the shortest possible number of interleaves!

Let's write `interleaves [a,b,c]` as `<a,b,c>`. The expression `<<0,2>,<1,3>,4>` expands to `<0,1,4l,2,3,4r>` where the `l` and `r` suffix means that we have "uninterleaved" `4` into a left and right part.

I did a benchmark on `<<0,2>,<1,3>,4>` vs `<0,1,4l,2,3,4r>`, and the expanded version is 20-30% faster. I imagine that it gets significantly sweeter when expressions get more complex!

**Comment by BlackCapCoder** [comment]
> What's an application for `interleaveMany`?
My application is simply number theoretic where I want every subsequent stream to be drawn from half as often. That very well could be too niche; I figured I'd share anyways. I appreciate you taking the time to reply to these every day!

> How did you measure performance?
I compiled `print $ interleaveMany someList !! some_large_number` and ran `time cabal run` and `memusage cabal run`

> I'd rather avoid a new entity, even if your implementation is a bit faster.
I agree. That said, I am getting very promising results for `interleave` fusion with exponential speed-up in some cases, but I'll leave that out of this PR

**Comment by Bodigrim** [comment]
Thanks for sharing, but I'm afraid it is too niche. Sorry for this.

**Pull request closed without merging**
